### PR TITLE
Training

### PR DESCRIPTION
**Pull request by soumik12345**

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
There seems to be some problem with the `SSIMMetric` leading to a `ValueError: Negative dimension size caused by subtracting ... input shapes: [8,8,8,3], [11,11,?,1]`. Simply changing the `filter_size` argument of `tf.image.ssim(...)` from 11 (default) to 8 fixed the issue. This was checked on a Google Colab (Tesla T4). A partial run can be found [here](https://wandb.ai/sauravmaheshkar/mirnetv2/runs/156scfrl).

```diff
+  ssim = tf.image.ssim(y_true, y_pred, max_val=self.max_val, filter_size=8)
-  ssim = tf.image.ssim(y_true, y_pred, max_val=self.max_val)
```


I also added `wandb/` and `artifacts/` to `.gitignore`.

**Comment by soumik12345** [comment]
> There seemed to be some problem with the `SSIMMetric` leading to a `ValueError: Negative dimension size caused by subtracting ... input shapes: [8,8,8,3], [11,11,?,1]`. Simply changing the `filter_size` argument of `tf.image.ssim(...)` from 11 (default) to 8 fixed the issue. This was checked on a Google Colab (Tesla T4). A partial run can be found [here](https://wandb.ai/sauravmaheshkar/mirnetv2/runs/156scfrl).
> 
> ```diff
> +  ssim = tf.image.ssim(y_true, y_pred, max_val=self.max_val, filter_size=8)
> -  ssim = tf.image.ssim(y_true, y_pred, max_val=self.max_val)
> ```
> 
> I also added `wandb/` and `artifacts/` to `.gitignore`.

Thanks @SauravMaheshkar 
I will run a couple of runs (till 150 epochs) with the CLI to confirm everything is working correctly.
In the meantime, can you please take a look at [this](https://colab.research.google.com/drive/1VdpUrfv009TJ_gwy6HgzmNd8IWv0kSGg?usp=sharing) notebook for parity of the code written in the repository with that in the notebook? I actually used this notebook to train the model originally with the respective runs in the workspace (not on Colab, but on VertexAI), so I am not sure why it was necessary to explicitly specify the `filter_size` while computing structural similarity.

**Comment by SauravMaheshkar** [comment]
This is interesting. Can it be because of version mismatch ? What is the tensorflow and keras version on Vertex AI ?

Were the CLI runs successful ?

**Review by soumik12345 — COMMENTED** [review]
@SauravMaheshkar Thanks for the updates. I think we're ready to merge.

**Pull request merged**
